### PR TITLE
Adds support for is_paused_upon_creation flag when creating a dag

### PR DESCRIPTION
**Pull request by zohairshaikh**

### CODE REVIEW

**Comment by zohairshaikh** [comment]
Tested manually

**Comment by ajbosco** [comment]
@zohairshaikh looks like it needs to be formatted to pass CI. Can you update your PR?

**Comment by zohairshaikh** [comment]
@ajbosco done. Ran `black dagfactory/dagbuilder.py`

Screenshot 2021-12-23 at 7 51 56 PM

**Comment by ajbosco** [comment]
Thanks!

**Pull request merged**
