### PR TITLE
Add new params which can be defined in DAG

### PR DESCRIPTION
**Pull request by withsmilo**
I added the following params newly.
* end_date
* concurrency
* default_view
* orientation
* on_success_callback
* on_failure_callback
* retry_delay

### CODE REVIEW

**Comment by ajbosco** [comment]
Thanks, again!

**Comment by withsmilo** [comment]
@ajbosco 
Thanks for quick merging! Would you please release new version with my patches?

**Comment by ajbosco** [comment]
@withsmilo just published v0.4.0 with your patches.

**Comment by withsmilo** [comment]
@ajbosco Thank you very much!

**Pull request merged**
