### PR TITLE
Add support for python_callable_file for BranchPythonOperator

### PR DESCRIPTION
**Pull request by the-cybersapien**
The [BranchPythonOperator](https://airflow.apache.org/docs/apache-airflow/stable/concepts.html?highlight=branch#branching) follows the same concepts as the python operator and requires a `python_callable` method as well.

Currently, the special handling for `python_callable_file` and `python_callable_name` is only available for `PythonOperator`. This PR adds the same functionality for BranchPythonOperator as well

### CODE REVIEW

**Comment by the-cybersapien** [comment]
Hi @ajbosco, Please review this.

**Review by ajbosco — APPROVED** [review]

**Comment by ajbosco** [comment]
> Hi @ajbosco, Please review this.

Looks like it isn't passing the formatter. Can you run black against the code and I'll merge it?

**Comment by the-cybersapien** [comment]
@ajbosco have updated the PR after reformatting with black. Please approve the workflow and merge.

**Comment by ajbosco** [comment]
Thank you!

**Pull request merged**
