### PR TITLE
Support response_check callable in HttpSensor

### PR DESCRIPTION
**Pull request by ilaichi**
I have tested it for both success and failure of the sensor. This is the DAG YAML.

```
    task_3:
      operator: airflow.providers.http.sensors.http.HttpSensor
      task_id: 'http_sensor'
      http_conn_id: 'test-http'
      endpoint: ''
      method: 'GET'
      headers: 
        header1: 'value1'
      response_check_name: check_sensor
      response_check_file: /opt/airflow/dags/repo/dags/example1/http_conn.py
      poke_interval: 5
      timeout: 12        
      dependencies: [task_1]
```

### CODE REVIEW

**Comment by ilaichi** [comment]
Closes #96

**Comment by ilaichi** [comment]
I am not sure what the problem is with this build. This fix worked for me. HttpSensor reference here - https://airflow.apache.org/docs/apache-airflow-providers-http/stable/_api/airflow/providers/http/sensors/http/index.html

**Comment by ajbosco** [comment]
I think the http_provider needs to be added as a dependency now. https://github.com/apache/airflow/blob/main/setup.py#L342

**Comment by ilaichi** [comment]
I have updated tox.ini and Dockerfile to add HTTP provider in 2.0, and the build is passing locally. Let me know if this is not the correct way. 

They changed the packages in 2.0 to providers. I am using the old package now, which is linked to the providers in 2.0.

**Comment by ilaichi** [comment]
Please note that the http provider package install is breaking from airflow 2.0 to 2.1 for certain versions of the http provider (1.1.1 to 2.0.0). I am not sure if that is a problem - the dependency version resolution may take care of it.  

https://airflow.apache.org/docs/apache-airflow-providers-http/stable/index.html

**Comment by ilaichi** [comment]
I can try undoing my dependency changes and using the setup.py that you suggested.

**Comment by ilaichi** [comment]
Can you run a build now?

**Comment by ajbosco** [comment]
I think we still need to add `http` here otherwise installs from pypi will fail. https://github.com/ajbosco/dag-factory/blob/master/setup.py#L26

**Comment by ilaichi** [comment]
Let me add that in setup.py

**Comment by ilaichi** [comment]
Actually, the http sensor moved to providers in version 2.0. 

Would this be correct? 
```
REQUIRED = ["apache-airflow[http,kubernetes]>=1.10.0", "pyyaml", "packaging"] 
```

Or should we split the dependency conditionally?
```
REQUIRED = ["apache-airflow[kubernetes]>=1.10.0, <2.0.0", "apache-airflow[http,kubernetes]>=2.0.0","pyyaml", "packaging"] 
```

**Comment by ajbosco** [comment]
> Actually, the http sensor moved to providers in version 2.0.
> 
> Would this be correct?
> 
> ```
> REQUIRED = ["apache-airflow[http,kubernetes]>=1.10.0", "pyyaml", "packaging"] 
> ```
> 
> The build passes with this in my setup, but I am not sure if it will cause any issues in certain scenarios.

I think the first one is what we want.

**Comment by ilaichi** [comment]
> > Actually, the http sensor moved to providers in version 2.0.
> > Would this be correct?
> > ```
> > REQUIRED = ["apache-airflow[http,kubernetes]>=1.10.0", "pyyaml", "packaging"] 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The build passes with this in my setup, but I am not sure if it will cause any issues in certain scenarios.
> 
> I think the first one is what we want.

I am not sure what you mean. Do you mean to leave out the change in setup.py?

**Comment by ajbosco** [comment]
This is what is needs to be added to setup.py

```
REQUIRED = ["apache-airflow[http,kubernetes]>=1.10.0", "pyyaml", "packaging"] 
```

**Review by ajbosco — APPROVED** [review]
Awesome work! Thanks!

**Comment by ilaichi** [comment]
Do we need to update the version numbers anywhere?

**Comment by ilaichi** [comment]
Will you be creating a new version? Is it included via the standard "pip install"?

**Comment by ajbosco** [comment]
> Will you be creating a new version? Is it included via the standard "pip install"?

@ilaichi Yeah, I'll cut a new release today

**Comment by ilaichi** [comment]
> > Will you be creating a new version? Is it included via the standard "pip install"?
> 
> @ilaichi Yeah, I'll cut a new release today

Can I help in any way?

**Comment by ajbosco** [comment]
> > > Will you be creating a new version? Is it included via the standard "pip install"?
> > 
> > 
> > @ilaichi Yeah, I'll cut a new release today
> 
> Can I help in any way?

v0.10.0 was just pushed to pypi

**Pull request merged**
