### PR TITLE
Added dynamic task mapping *DRAFT*

### PR DESCRIPTION
**Pull request by matveykortsev**
Added basic support for dynamic task mapping. Any suggestions and contributions are welcome!

### CODE REVIEW

**Review by ajbosco — COMMENTED** [review]
Supporting all the different versions of Airflow is getting quite...wild. Maybe it is time to just support 2.3+ and make a 1.0 release.

**Comment by matveykortsev** [comment]
I'm partially agree with you, but I think cutting on 2.3 its too much for now because last year airflow released updates quite fast.
But I think removing the support of Airflow < 2.0.0 will be a good idea.

**Review by ajbosco — APPROVED** [review]
Nice work!

**Comment by matveykortsev** [comment]
Can you cut the release? I will add documentation later this week for dynamic task mapping

**Comment by ajbosco** [comment]
> Can you cut the release? I will add documentation later this week for dynamic task mapping

A new `0.18.0` version was just released. Thanks for the PRs!

**Pull request merged**
